categories:
  - aceite vegetal
  - arroz
  - atun
  - azucar
  - banano
  - cafe
  - cebolla
  - cerveza
  - frijoles
  - harina de trigo
  - huevos
  - leche
  - manzanas
  - pan
  - papa
  - pasta seca
  - pollo entero
  - queso blanco
  - refresco de cola
  - tomates

synonyms:
  "leche liquida": leche
  "leche líquida": leche
  "leches": leche
  "leche entera": leche
  "leche descremada": leche
  "leche deslactosada": leche
  "leche semidescremada": leche
  "leche semi descremada": leche
  "leche en polvo": leche
  "atun en lata": atun
  "atún en lata": atun
  "atun lata": atun
  "atún lata": atun
  "atun en aceite": atun
  "atún en aceite": atun
  "atun en agua": atun
  "atún en agua": atun
  "latas de atun": atun
  "latas de atún": atun
  "pan de molde": pan
  "pan molde": pan
  "panes": pan
  "pan tajado": pan
  "pan tajado bimbo": pan
  "pan blanco": pan
  "pan integral": pan
  "pan artesanal": pan
  "pan de caja": pan
  "pan rebanado": pan
  "cebollas": cebolla
  "cebolla cabezona": cebolla
  "cebolla blanca": cebolla
  "cebolla morada": cebolla
  "cebolla larga": cebolla
  "cebolla junca": cebolla
  "papas": papa
  "papa criolla": papa
  "papas criollas": papa
  "papa pastusa": papa
  "papa sabanera": papa
  "papa roja": papa
  "papa blanca": papa
  "papa pelada": papa
  "papa para freir": papa
  "papa para freír": papa
  "papas fritas": papa
  "papa empacada": papa
  "café": cafe
  "café molido": cafe
  "cafe molido": cafe
  "cafe instantaneo": cafe
  "café instantáneo": cafe
  "cafe soluble": cafe
  "café soluble": cafe
  "cafe en grano": cafe
  "café en grano": cafe
  "cafe tostado": cafe
  "café tostado": cafe
  "cafe molido oscuro": cafe
  "cafe descafeinado": cafe
  "café descafeinado": cafe
  "azucar": azucar
  "azucar blanca": azucar
  "azucar morena": azucar
  "azucar refinada": azucar
  "azucar rubia": azucar
  "azucar pulverizada": azucar
  "azucar glass": azucar
  "azucar glas": azucar
  "bananos": banano
  "banana": banano
  "bananas": banano
  "plátano": banano
  "platano": banano
  "plátanos": banano
  "platanos": banano
  "guineo": banano
  "guineos": banano
  "aceite vegetal": aceite vegetal
  "aceite 123": aceite vegetal
  "aceites": aceite vegetal
  "aceite vegetal comestible": aceite vegetal
  "aceite de cocina": aceite vegetal
  "aceite de girasol": aceite vegetal
  "aceite de canola": aceite vegetal
  "aceite de soya": aceite vegetal
  "aceite de maiz": aceite vegetal
  "aceite de maíz": aceite vegetal
  "aceite comestible": aceite vegetal
  "aceite para freir": aceite vegetal
  "aceite para freír": aceite vegetal
  "aceite premium": aceite vegetal
  "aceite en botella": aceite vegetal
  "huevos": huevo
  "huevo blanco": huevo
  "huevo": huevo
  "huevo rojos": huevo
  "huevo rojo": huevo
  "huevo de gallina": huevo
  "huevo de campo": huevo
  "huevos de gallina": huevo
  "huevo aa": huevo
  "huevo a": huevo
  "docena de huevos": huevo
  "carton de huevo": huevo
  "cartón de huevo": huevo
  "bandeja de huevos": huevo
  "frijol": frijoles
  "fríjol": frijoles
  "fríjoles": frijoles
  "frijol rojo": frijoles
  "frijol negro": frijoles
  "óleo vegetal": aceite vegetal
  "atum": atun
  "açúcar": azucar
  "banana": banano
  "cebola": cebolla
  "cerveja": cerveza
  "feijão": frijoles
  "farinha de trigo": harina de trigo
  "ovos": huevos
  "leite": leche
  "maçãs": manzanas
  "pão": pan
  "batata": papa
  "macarrão": pasta seca
  "frango inteiro": pollo entero
  "queijo branco": queso blanco
  "refrigerante de cola": refresco de cola
  

exclude_keywords:
  - gift card
  - tarjeta regalo
  - servicio
  - instalación
  - membresía
  - recarga
  - garantía
  - warranty
  - accesorio
  - funda
  - repuesto
